%Set preferences with setdbprefs.
setdbprefs('DataReturnFormat', 'cellarray');
setdbprefs('NullNumberRead', 'NaN');
setdbprefs('NullStringRead', 'null');


%Make connection to database.  Note that the password has been omitted.
%Using ODBC driver.
conn = database('MSSQLSERVER', 'sa', 'GMB2015');

%Read data from database.
curs = exec(conn, ['SELECT 	MesureFEMTO.id'...
    ' ,	MesureFEMTO.DataSet'...
    ' ,	MesureFEMTO.FileName'...
    ' ,	MesureFEMTO.AtTime'...
    ' ,	MesureFEMTO.SamplingTime'...
    ' ,	MesureFEMTO.VibHorMoy'...
    ' ,	MesureFEMTO.VibVerMoy'...
    ' ,	MesureFEMTO.VibMoy'...
    ' ,	MesureFEMTO.VibHorVar'...
    ' ,	MesureFEMTO.VibVerVar'...
    ' ,	MesureFEMTO.VibVar'...
    ' ,	MesureFEMTO.TemperatureMoy'...
    ' ,	MesureFEMTO.TemperatureVar'...
    ' FROM 	Pronostia.dbo.MesureFEMTO '...
    ' where dataset=''TrnBearing1_1'' order by id ']);

curs=curs;
curs = fetch(curs);
close(curs);

%Assign data to output variable
DataTab = curs.Data;

%Close database connection.
close(conn);

%Clear variables
clear curs conn